// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7FVnhAAPgJQfjHytFZRsLfNFGoZKN8CU',
    appId: '1:292243415871:web:f122cac1fa7a585586a98a',
    messagingSenderId: '292243415871',
    projectId: 'aifacerecognition-a3223',
    authDomain: 'aifacerecognition-a3223.firebaseapp.com',
    storageBucket: 'aifacerecognition-a3223.appspot.com',
    measurementId: 'G-EENM8VQ5N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPZ5IcK0BnEgjgMFUWZk5BeliYy1gnM6k',
    appId: '1:292243415871:android:8000f89a8344f20686a98a',
    messagingSenderId: '292243415871',
    projectId: 'aifacerecognition-a3223',
    storageBucket: 'aifacerecognition-a3223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyAn8io0RwmBx6nloexLXHx6dCoDIqVOA',
    appId: '1:292243415871:ios:68c3b21bf2ec77e786a98a',
    messagingSenderId: '292243415871',
    projectId: 'aifacerecognition-a3223',
    storageBucket: 'aifacerecognition-a3223.appspot.com',
    iosBundleId: 'com.example.statApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyAn8io0RwmBx6nloexLXHx6dCoDIqVOA',
    appId: '1:292243415871:ios:68c3b21bf2ec77e786a98a',
    messagingSenderId: '292243415871',
    projectId: 'aifacerecognition-a3223',
    storageBucket: 'aifacerecognition-a3223.appspot.com',
    iosBundleId: 'com.example.statApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7FVnhAAPgJQfjHytFZRsLfNFGoZKN8CU',
    appId: '1:292243415871:web:eb67f3422249f44e86a98a',
    messagingSenderId: '292243415871',
    projectId: 'aifacerecognition-a3223',
    authDomain: 'aifacerecognition-a3223.firebaseapp.com',
    storageBucket: 'aifacerecognition-a3223.appspot.com',
    measurementId: 'G-95Q7Z65YD2',
  );
}
